# Generated by Django 4.1.1 on 2022-09-15 16:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='LNMLoan',
        ),
    ]
